### ISSUE TITLE
Parsing error with date without day if current day is not in to be parsed month

### ISSUE THREAD

**Issue by dArignac** [dateutil/dateutil#173] opened 2016-01-31 07:45 UTC
Today is 2016-01-31.
I try to parse the string 2004-11 to a date:

```
parser.parse('2004-11')
```

This fails with

```
ValueError: day is out of range for month
```

as the parsing method is using the current day for the missing day in the to be parsed string. But unfortunately there is no 31st of November, so I internally simply ```datetime.datetime(2004,11,31)``` fails as the date does not exist.

I suggest to set the day either to the last day of the month of the parsed date in this case, or generally to the first day of the month.

**Comment by pganssle** [comment] 2016-01-31 16:08
Duplicate of Issue #25. Fixed in PR #30. Will be part of next release, even though portions of #30 will likely be rolled back per Issue #169.

**Closed** 2016-01-31 16:09 UTC
Labels: bug, duplicate, parser
