### ISSUE TITLE
Relativedelta constructed from fractions of hours... (Feature request)

### ISSUE THREAD

**Issue by ghost** [dateutil/dateutil#40] opened 2015-02-23 12:00 UTC
I would like to request feature to allow relativedelta construction from e.g. hour fractions.
In some business applications I met the practice to store total hours count represented as float. In one even as total days count (represented by float). Now I need to integrate with them.
thx

**Comment by pganssle** [comment] 2015-02-23 18:41
@babbbrak I'm not sure how much bearing it would have on the implementation of this sort of thing, but how would you recommend dealing with a situation where a smaller value is specified along with a fractional value? E.g. 1.48 days = 1 day, 11 hours, 31 minutes, 12 seconds. If I specify: `relativedelta(days=1.48, seconds=4)`, should the `seconds` keyword override the days, vice-versa, or should an error be thrown?

I'm also a little concerned with the possibility that people might not be paying attention to their data types and pass a float that has a rounding error in it, causing unexpected behavior in the implementation.

One possible suggestion I have would be to add a submodule for float-to-ordinal and ordinal-to-float conversions. I think this might have wider uses (there are a few places this comes up in `parser`, for example), and it would let you choose your own default fallback positions if you pass the outputs to a `relativedelta`.

**Comment by ryanss** [comment] 2015-03-29 02:35
I believe you can close this issue as this is already how `relativedelta` works:

```python
>>> datetime(2015, 1, 1) + relativedelta(days=1.5)
datetime.datetime(2015, 1, 2, 12, 0)
>>> datetime(2015, 1, 1) + relativedelta(hours=1.5)
datetime.datetime(2015, 1, 1, 1, 30)
>>> datetime(2015, 1, 1) + relativedelta(hours=1.5, minutes=4)
datetime.datetime(2015, 1, 1, 1, 34)
```

@pganssle In your example `relativedelta(days=1.48, seconds=4)` nothing is overwritten, the seconds from the partial `days` and the `seconds` parameters are added together:

```python
>>> datetime(2015, 1, 1) + relativedelta(days=1.48, seconds=4)
datetime.datetime(2015, 1, 2, 11, 31, 16)
```

**Comment by pganssle** [comment] 2015-03-29 19:20
@ryanss Good catch, but I think that the support actually should be made more explicit. Right now, it's basically a coincidence that this works, because `relativedelta` doesn't explicitly check if it's been given a float or an integer, and all relative information at the level of a day or smaller are first cast to `timedelta` during addition operations. When a `timedelta` object is passed a fractional argument, it converts the remaining fraction to seconds (which is added to the existing seconds argument). So:

    >>> timedelta(days=1.48, seconds=4)
    datetime.timedelta(1, 41476)

This doesn't work if you use anything bigger than a week, though (weeks are implictly converted to days), since those are manually converted and expecting an `int`:

    >>> rd = relativedelta.relativedelta(months=1.5)
    >>> datetime(2014, 1, 1) + rd
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-6-245d768deca6> in <module>()
    ----> 1 datetime(2014, 1, 1) + rd

    dateutil\relativedelta.pyc in __radd__(self, other)
         317     def __radd__(self, other):
    --> 318         return self.__add__(other)
        320     def __rsub__(self, other):

    dateutil\relativedelta.pyc in __add__(self, other)
        288                 year -= 1
        289                 month += 12
    --> 290         day = min(calendar.monthrange(year, month)[1],
        291                   self.day or other.day)
        292         repl = {"year": year, "month": month, "day": day}

    C:\Python27\lib\calendar.pyc in monthrange(year, month)
        119     if not 1 <= month <= 12:
        120         raise IllegalMonthError(month)
    --> 121     day1 = weekday(year, month, 1)
        122     ndays = mdays[month] + (month == February and isleap(year))
        123     return day1, ndays

    C:\Python27\lib\calendar.pyc in weekday(year, month, day)
        111     """Return weekday (0-6 ~ Mon-Sun) for year (1970-...), month (1-12),
        112        day (1-31)."""
    --> 113     return datetime.date(year, month, day).weekday()

    TypeError: integer argument expected, got float

I think that if we want to support this sort of thing, then it needs to work for all relative arguments, and at the very least `relativedelta.__repr__` needs to be updated to reflect the fact that this is happening:

    >>> rd = relativedelta.relativedelta(days=1.48, seconds=4)
    >>> rd
    relativedelta(days=+1, seconds=+4)

    >>> rd.days, rd.seconds
    (1.48, 4)

The other problem is that *absolute* information arguments (`year`, `month`, `day`), *also* accept floats, but can't actually handle them.

I think that my plan moving forward on this is to do 3 things for the 2.5.0 release:
1. Add a deprecation warning when constructing `relativedelta` objects using absolute floats, indicating that this will no longer be possible in future releases.
2. Add explicit support for relative floats of all sizes, applied only during the actual arithmetic operations (e.g. `relativedelta(days=1.5, hours=2)` will store `days` as 1.5 and `hours` as 2 rather than storing `days` as 1 and `hours` as 14). This will be reflected in the `__repr__` method.
3. Add a method which takes a `relativedelta` object with floating point relative arguments and returns an equivalent representation using only integer values for each argument. This will work like `timedelta`, with each relative argument adding to lower ones if necessary.

**Comment by pganssle** [comment] 2015-04-22 16:02
After finally taking a crack at implementing this, I realized that the obvious reason why fractional `months` and `years` are not implemented in `timedelta` is that a "month" and a "year" are not well-defined. I'll need to re-consider the plan, but I think explicitly raising an error for undefined concepts like "1.5 months" is reasonable.

It's worth thinking about whether we want there to be a canonical representation including the fractions, like:

```python
>>> r = relativedelta(days=1.5, minutes=30)
relativedelta(days=1, hours=12, minutes=30)
>>> r.days = 2.0
>>> print(r)
relativedelta(days=2.0, minutes=30)
```

or if, once distributed among the shorter units, the "remainders" are treated separately, like:

```python
>>> r = relativedelta(days=1.5, minutes=30)
>>> print(r)
relativedelta(days=1, hours=12, minutes=30)
>>> r.days = 2.0
>>> print(r)
relativedelta(days=2.0, hours=12, minutes=30)
```

**Comment by pganssle** [comment] 2016-02-24 21:19
Done in #190.

**Closed by pganssle** 2016-02-24 21:19 UTC
Labels: enhancement, relativedelta
