### ISSUE TITLE
parse question, obtaining the strptime format.

### ISSUE THREAD

**Issue by apiszcz** [dateutil/dateutil#922] opened 2019-06-18 14:24 UTC
Is it possible to create a strptime format string in the parser?
If not: Would it be possible to build one based on the format deduced from the parser?
If possible that format string could be used to define a field specific datetime object creation. So we use datutil.prase to understand the format, and if all are the same in the column, we then create datetime.datetime objects directly. 

dateutil parse is the most flexible for detecting time format,s however it is also the slowest, ~10K/SEC, vs datetime.datetime creation where I am measuring ~200K/second.

Perhaps the format string is in parser.py?

**Comment by jbrockmendel** [comment] 2019-06-18 15:46
This has been discussed a few times but never implemented.  I think there's a general consensus that this would be nice, but not so much on how to get there from here.  If you'd like to give it a try, go for it.

**Comment by pganssle** [comment] 2019-06-19 15:21
@apiszcz Indeed this would be ideal. One of the bigger problems with this is that `dateutil`'s parser does things that cannot be accurately captured in an `strptime` string, like detecting time zones or setting the value of `fold` in the parsed string.

Having a way to output the parser's format is definitely a goal, though.

I will close this issue as a duplicate of #125, and further discussion can take place on that ticket.

**Closed by pganssle** 2019-06-19 15:21 UTC
