### ISSUE TITLE
tzwin for the same timezone string does not compare equal

### ISSUE THREAD

**Issue by aburgm** [dateutil/dateutil#151] opened 2015-11-18 23:35 UTC
Consider this:

```
>>> dateutil.tz.gettz('Eastern Standard Time') == dateutil.tz.gettz('Eastern Standard Time')
False
```

Other timezone classes such as tzfile or tzlocal compare equal:

```
>>> dateutil.tz.gettz('America/New_York') == dateutil.tz.gettz('America/New_York')
True
>>> dateutil.tz.gettz('America/New_York') == dateutil.tz.gettz('America/Halifax')
False
>>> dateutil.tz.tzlocal() == dateutil.tz.tzlocal()
True
```

Note that, as a consequence of this, the expression ```dateutil.tz.gettz('UTC') == dateutil.tz.gettz('UTC')``` will return different results on different platforms (False on Windows, True on Unices).

**Comment by pganssle** [comment] 2015-11-19 00:04
Hmm.. I thought this was a dupe of one of the other tzwin bugs, recently reported by @labrys, but I guess it's a distinct thing. Thank you for the report.

As a note on scheduling, I'm hoping that I'll be able to get to all this time zone stuff the first week of December. Unfortunately it won't be before that. Recommended reading for anyone who is going to dig into this, #148, #144, #135, #143 and #132.

**Comment by labrys** [comment] 2015-11-19 00:16
Appreciate the update.  Thanks yet again for all your hard work on this, it is much appreciated!

**Closed** 2016-02-20 22:31 UTC
Labels: bug, time zones
