### ISSUE TITLE
rrule __str__ strips timezone information

### ISSUE THREAD

**Issue by jamesmallen** [dateutil/dateutil#603] opened 2018-01-02 16:34 UTC
If an `rrule` is created with timezone information in `DTSTART`, it appears to function correctly, but converting it back to a `str` removes the timezone information from `DTSTART`.

```python
>>> from dateutil.rrule import rrulestr
>>> str(rrulestr('DTSTART:20180102T120000Z\nFREQ=DAILY'))
'DTSTART:20180102T120000\nFREQ=DAILY'
```

Expected output:
`DTSTART:20180102T120000Z\nFREQ=DAILY`

OS: Alpine Linux 3.7
dateutil version 2.6.1
Python 3.6.3

I am using RRULE strings to store date/time information in a database. For now, I'm working around this by managing `DTSTART` separately from the RRULE strings and stripping it when serializing/deserializing the RRULE.

**Comment by pganssle** [comment] 2018-01-02 17:10
Duplicate of #348. This is a somewhat complicated question, since it's not actually possible to do this in a general way. I'm also not enthused, in general, about the idea of having time zones in `rrule`, since it seems ill-defined and may lead to bugs (since `rrule` is basically doing "wall time" manipulations and doesn't really handle ambiguous times well). Some consideration will need to be made as to how best to handle this, with reference to the RFC.

I think the best way to handle it is to use naive datetimes for the `rrule` and store the appropriate time zone separately, to be applied to the **results** of the `rrule`, not the inputs.

**Closed by pganssle** 2018-01-02 17:10 UTC
Labels: duplicate, enhancement, rrule
