### ISSUE TITLE
No way of generating recurrences backwards?

### ISSUE THREAD

**Issue by unaizalakain** [dateutil/dateutil#108] opened 2015-08-15 06:27 UTC
I can generate recurrences forwards…

```
future = datetime.now()
while True:
    future = recurrences.after(future, inc=True)
    if future is None:
        return
    yield future
```

…but AFAIU `rrule.before()` can't generate recurrences backwards, it needs an initial date and it will generate recurrences from that date onwards. Does dateutil provide some way of doing this? If not, could something similar be added?

The only workaround I can see at this stage is to generate recurrences for some time span, feed them into a `queue.PriorityQueue` where they get ordered and yield them from there.

**Comment by pganssle** [comment] 2015-08-17 12:49
Duplicate of #37. This is difficult to do with the current method of generating ``rrule``s mainly because the logic isn't designed to be bidirectional. It's definitely on the list of things to do, probably together with @jarondl's plan to implement an `rrule2` (#15).

**Closed** 2015-08-17 12:49 UTC
Labels: duplicate, enhancement, rrule
