### ISSUE TITLE
p.DEFAULTPARSER.parse('feb') error on Jan 29-31

### ISSUE THREAD

**Issue by firecat53** [dateutil/dateutil#174] opened 2016-01-31 18:38 UTC
Just noticed this a couple of days ago:

    >>> import dateutil.parser as p
    >>> p.DEFAULTPARSER.parse('feb')
    /usr/lib/python2.7/site-packages/python_dateutil-1.5-py2.7.egg/dateutil/parser.pyc in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
    308             if value is not None:
    309                 repl[attr] = value
    --> 310         ret = default.replace(**repl)
    311         if res.weekday is not None and not res.day:
    312             ret = ret+relativedelta.relativedelta(weekday=res.weekday)
    ValueError: day is out of range for month

Works fine parsing 'jan' or 'mar'. I wonder if this would also fail on the 31st of the month if the next month only had 30 days?

Thanks,
Scott
dateutil version 2.4.2

**Comment by pganssle** [comment] 2016-02-11 16:04
Duplicate of Issue #25. Fixed in PR #30. Will be part of next release, even though portions of #30 will likely be rolled back per Issue #169.

**Closed by pganssle** 2016-02-11 16:04 UTC
