### ISSUE TITLE
RRule next occurence computation

### ISSUE THREAD

**Issue by arctarus44** [dateutil/dateutil#827] opened 2018-10-24 15:26 UTC
# Summary

In some case, when I use the ``after`` method to compute the next occurrence of a rrule. The occurrence returned is not correct : 1 day is added to the expected occurrence start.

Did I do something wrong ?

## How to reproduce

```python
#!/bin/env python2.7

from dateutil import tz
from datetime import datetime
from dateutil.rrule import rrulestr

rrule = "FREQ=WEEKLY;BYDAY=FR"
rrule_start = 1536880500  # Thursday 13 September 2018 23:15:00 UTC

from_now = 1539846000  # Thursday 18 October 2018 07:00:00 UTC

dt_start = datetime.utcfromtimestamp(rrule_start).replace(tzinfo=tz.UTC)

dt_after = datetime.utcfromtimestamp(from_now).replace(tzinfo=tz.UTC)

occ = rrulestr(rrule, dtstart=dt_start).after(dt_after)
print("Rrule start {}.".format(dt_start))
print("First occurence after {} : {}.".format(dt_after, occ))
```
## Current behavior
For a rrule "FREQ=WEEKLY;BYDAY=FR" with a start date at Thursday 13 September 2018 23:15:00 UTC, when I compute the next occurrence after the Thursday 18 October 2018 07:00:00 UTC the next occurrence returned is 2018-10-19 23:15:00+00:00.

## Expected behavior
The ``after`` method should have returned an occurrence that start at 2018-10-19 23:15:00+00:00.

## Additional informations
 - dateutil : 2.7.3
 - python : 2.7.9

**Comment by pganssle** [comment] 2018-10-24 15:54
@arctarus44 I don't understand the issue, you say the current behavior is that it returns `2018-10-19 23:15:00+00:00`, and the current behavior is that it returns `2018-10-19 23:15:00+00:00`. Seems like it works?

**Comment by pganssle** [comment] 2018-10-24 15:57
Also I've edited your example to avoid using `pytz`, since that makes it easier to reproduce without having `pytz` installed. I am obliged to mention that [you should not use `pytz` when you could use `dateutil.tz` anyway](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html).

Also, perhaps you don't know this, but `datetime.datetime.fromtimestamp` takes an optional `tz` argument, so these lines:

```python
dt_start = datetime.utcfromtimestamp(rrule_start).replace(tzinfo=tz.UTC)
dt_after = datetime.utcfromtimestamp(from_now).replace(tzinfo=tz.UTC)
```

Can be replaced with:

```python
dt_start = datetime.fromtimestamp(rrule_start, tz=tz.UTC)
dt_after = datetime.fromtimestamp(from_now, tz=tz.UTC)
```

It is much faster that way. As a general rule, `utcnow` and `utcfromtimestamp` can be replaced with `now(UTC)` and `fromtimestamp(ts, UTC)` (where `UTC` is either `datetime.timezone.UTC` in Python 3 or `dateutil.tz.UTC` in either Python 2 or 3).

**Comment by arctarus44** [comment] 2018-10-24 16:09
Thank you for your advices.

I am sorry, I made a mistake. With the current behavior I get ``2018-10-19 23:15:00+00:00`` when I expect ``2018-10-18 23:15:00+00:00``.

**Comment by pganssle** [comment] 2018-10-24 16:21
@arctarus44 The RRULE you have written specifies that recurrences only happen on Fridays (BYDAY=FR), since `2018-10-18` is a Thursday, no recurrence occurs on that day. The next recurrence after `2018-10-18` is Friday, 19 October 2018, so this is not a bug.

I'm not quite sure what you are trying to accomplish here, but I can help you design a new RRULE if the one you've written isn't giving you what you want. Why are you restricting your RRULE to Fridays if you want it returning some recurrences on a Thursday?

(By the way, this does not seem to be a bug in the library, so I'm going to close this issue, but we can continue to use this issue to help you figure out what needs to change in your code).

**Closed by pganssle** 2018-10-24 16:21 UTC
Labels: rrule

**Comment by arctarus44** [comment] 2018-10-24 19:45
Thank you, you pinpoint the bug I was trying to fix. 

This situation is the result of the definition of a rrule while using the Paris timezone, bad timezone handling and arcane code. The rrule I gave you earlier was originally designed to work on Friday 1h15.

I do not know by heart the rrule specification, but I think they are probably something to fix. In my opinion, the rrule computation should have returned None or the rrule instanciation should have raised an exception.

The DTSTART used to define the first occurrence refer to a Thursday and the rrule means repeat every Friday. So, it's logical, at least for me, to get no occurrence, because the rrule is not correctly defined. In the specification, it's written that the DTSTART is used to generate the set of occurrence, and they are no clear indication that only the time part of it is use for this.

Thank you for your time.

**Comment by pganssle** [comment] 2018-10-24 19:53
`DTSTART` does not have to be a valid instance of the rule, it's just the rule's base. `FREQ=WEEKLY` means "repeat every week" and `BYDAY=FR` means "on Friday". If you change that to `BYDAY=TU,TH`, it will repeat every week on Tuesday and Thursday.

RRULE is also weird in that the `BY` rules mean different things when the component is greater than or smaller than the canonical frequency, so for example `FREQ=YEARLY` generates one date per year, but `FREQ=YEARLY;BYYEARDAY=100,145,200` generates *three* dates per year, because `BY` components *smaller* than `FREQ` means "add these components on top of the main recurrence". On the other hand, if you do `FREQ=DAILY`, you will get one occurrence per day all year round, but `FREQ=DAILY;BYMONTH=12`, filters the daily rule down to "daily in the month of December", so you'll only get 31 instead of 365 days per year in this rule.

Hope that's helpful!

**Comment by pganssle** [comment] 2018-10-24 19:57
By the way, if you want something that happens every Friday at 13:15, I would not do it in UTC. You should do it this way:

```python
from datetime import datetime
from dateutil import rrule, tz

PARIS = tz.gettz('Europe/Paris')
dtstart = datetime(2018, 9, 18, 13, 15)
rr = rrule.rrule(freq=rrule.WEEKLY, byweekday=rrule.FR, dtstart=dtstart)
aware_dts = (x.replace(tzinfo=PARIS) for x in rr)
```

It works fine if you set `dtstart` to be aware (e.g. `dtstart = datetime(2018, 9, 10, 13, 15, tzinfo=PARIS)`), but there are some edge cases that are better avoided. Definitely do not use `pytz` time zones with `rrule`.

**Comment by arctarus44** [comment] 2018-10-24 20:10
Thank you a lot !

Your responses are extremely interesting and helpful

Have a nice day.

**Comment by saravanakumar-rogers** [comment] 2022-10-25 14:28
aware_dts = (x.replace(tzinfo=PARIS) for x in rr)  == what is x in this string ?
