### ISSUE TITLE
parser not returning none

### ISSUE THREAD

**Issue by jacoor** [dateutil/dateutil#137] opened 2015-10-29 20:06 UTC
print parser.parse('') returns parsed now()...

**Comment by pganssle** [comment] 2015-10-30 19:14
Closing as a duplicate of #78. This is not a bug per se as it is the documented behavior, but following the principle of least astonishment, it will change in python 2.5.0 to raising a `ValueError`.

**Closed by pganssle** 2015-10-30 19:14 UTC

**Comment by jacoor** [comment] 2015-10-30 19:18
Thanks for clarification.

2015-10-30 20:14 GMT+01:00 Paul Ganssle <notifications@github.com>:

> Closing as a duplicate of #78
> <https://github.com/dateutil/dateutil/issues/78>. This is not a bug per
> se as it is the documented behavior, but following the principle of least
> astonishment, it will change in python 2.5.0 to raising a ValueError.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dateutil/dateutil/issues/137#issuecomment-152621747>.
>



-- 
Jacek Ostański
Internet Evolution - Strony i serwisy Internetowe
608-230-735
