### ISSUE TITLE
Unexpected fuzzy parsing

### ISSUE THREAD

**Issue by pranayrpi** [dateutil/dateutil#161] opened 2015-12-18 22:40 UTC
Here is a string that I'm trying to parse using the parser submodule 

```
"2014-04-12 13:00:10 hkhakhsak 12"
```

```
>> res = parser.parse("2014-04-12 13:00:10 hkhakhsak 12", fuzzy=True)
>>> print res
2014-04-12 12:00:10

```

As you can see the hour value is replaced by 12. Our intuition however says that the hour value is 13. Is this something to be expected from the parser ?

**Comment by pganssle** [comment] 2016-01-11 18:37
@pranayrpi I think this is a duplicate of #31, which was resolved by #32 and will be included in the next release. Can you confirm that your issue is solved if you pull run it using the current version from Github?

**Closed** 2016-02-03 05:26 UTC
Labels: bug, duplicate, parser
