### ISSUE TITLE
Recognize timezones e.g "US/Eastern"

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#534] opened 2017-12-04 22:24 UTC
The colloquial "EST", "EDT", "PST", etc are technically ambiguous, but "US/Eastern", "US/Pacific", etc should be recognized by the parser.

**Comment by pganssle** [comment] 2017-12-05 00:37
I don't intend to hard-code any time zones into the parser, so in the end this just boils down to PR #227, which is only stalled because I was a bit worried about changes to the public interface and some minor efficiency concerns. It's on track for maybe 2.8.0 release.

Duplicate of #93.

**Closed by pganssle** 2017-12-05 00:37 UTC

**Comment by jbrockmendel** [comment] 2017-12-05 16:12
> so in the end this just boils down to PR #227, which is only stalled because I was a bit worried about changes to the public interface and some minor efficiency concerns

Sounds good.  Let me know if I can be useful.

> I don't intend to hard-code any time zones into the parser

Can you explain your thinking on this a little?  Is there some context in which "US/Pacific" etc are incorrect?  Or is it just less elegant than the implementation in #227?

**Comment by pganssle** [comment] 2017-12-05 16:46
> "Can you explain your thinking on this a little? Is there some context in which "US/Pacific" etc are incorrect? Or is it just less elegant than the implementation in #227?

I'm not interested in hard-coding *any* sort of data (with certain rare exceptions like `Z` and `UTC`, which are hard-coded into many actual *standards*). It's an improper separation of concerns, we should provide interfaces to data in well-known formats and try to be agnostic about the contents of the data. I'm not even particularly comfortable with the fact that we hard-code the days of the week (though there are many reasons why I'm not enthused about moving away from this at this point).

Rather than hard-code anything, we should have a generalized way to register lists of time zones, and by default we can construct the `parser` instance with a list that includes the IANA database names. (`tzinfos` is close, but it's really only intended for mapping shortnames to zones).
