### ISSUE TITLE
Regression Moving from Python 2 to Python 3

### ISSUE THREAD

**Issue by speedplane** [dateutil/dateutil#1075] opened 2020-08-28 04:55 UTC
I have recently started porting a code base from python 2 to 3, including `dateutil`. I've noticed there is a regression in behavior for some dates that are not perfectly formatted. In the examples below, it tries to parse `'Sep. 19,2013'`:

### Python 2 Behavior
```
import dateutil.parser
dateutil.parser.parse('Sep. 19,2013')
> datetime.datetime(2013, 9, 19, 0, 0)
````
### Python 3 Behavior
```
import dateutil.parser
dateutil.parser.parse('Sep. 19,2013')
> datetime.datetime(2020, 9, 19, 0, 0)
````

The Python 2 behavior appears to be more correct in this case. Is this type of imperfect date formatting supposed to be supported by dateutil? Any way to get the older behavior working in Python 3? We rely on some of this cleanup.

**Comment by ffe4** [comment] 2020-08-28 10:20
I could not reproduce this issue. First of all, if I use your import pattern, I get an error:

```pycon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dateutil' has no attribute 'parser'
```

If I use a working import pattern, I get the same result for both:

With `python-dateutil==2.8.1` on `Python 3.8.2`
```pycon
>>> from dateutil.parser import parse
>>> parse('Sep. 19,2013')
datetime.datetime(2020, 9, 19, 0, 0)
```

With `python-dateutil==2.8.1` on `Python 2.7.17`
```pycon
>>> from dateutil.parser import parse
>>> parse('Sep. 19,2013')
datetime.datetime(2020, 9, 19, 0, 0)
```

I also tried `python-dateutil==2.5.0`, with the same result.
Could you check your specific versions of both python and dateutil?

**Comment by speedplane** [comment] 2020-08-28 13:20
Hi @ffe4, 
Note: You're right about the import. The original import statements were working for me just because I had a built-in startup script that had imported dateutil.parser. I've edited the original issue.

However, the main issue remains the same. The original dateutil parser is very old, version 1.5.


### For Python 2
- Python 2.7.18.
- dateutil version 1.5 (it's very old)
```
>>> from dateutil.parser import parse
>>> parse('Sep. 19,2013')
datetime.datetime(2013, 9, 19, 0, 0)
```

### For Python 3
- Python 3.5.2
- dateutil version 2.8.1
```
In [7]: import dateutil; dateutil.parser.parse('Sep. 19,2013')
Out[7]: datetime.datetime(2020, 9, 19, 0, 0)
```

**Comment by speedplane** [comment] 2020-08-28 13:27
I can get it working in Python 3 if I do the following:

```
pip3 install --upgrade python-dateutil==1.5
2to3 -w /usr/local/lib/python3.5/dist-packages/dateutil/
python3
>>> from dateutil.parser import parse
>>> parse('Sep. 19,2013')
datetime.datetime(2013, 9, 19, 0, 0)
```

**Comment by pganssle** [comment] 2020-08-28 13:41
So this is not related to Python 2 or 3, it's just a change that happened in the parsing logic. I would guess around 2.4-ish.

This is a duplicate of #939

**Closed by pganssle** 2020-08-28 13:41 UTC
Labels: bug, parser
