### ISSUE TITLE
Can't parse "Tue, 27 Mar 2018 23:48:52 +0800 (GMT+08:00)"

### ISSUE THREAD

**Issue by ericlingit** [dateutil/dateutil#805] opened 2018-08-20 10:00 UTC
### Version
Python 3.6.5
python-dateutil (2.7.3)

### How to reproduce
```
import dateutil
dateutil.parser.parse('Tue, 27 Mar 2018 23:48:52 +0800 (GMT+08:00)')
```
### Expected output
```
datetime.datetime(2018, 3, 27, 23, 48, 52, tzinfo=tzoffset(None, 28800))
```

### Actual output
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-79-89007ab7b4cb> in <module>()
----> 1 dateutil.parser.parse('Tue, 27 Mar 2018 23:48:52 +0800 (GMT+08:00)')

~/venvs/env01/lib/python3.6/site-packages/dateutil/parser/_parser.py in parse(timestr, parserinfo, **kwargs)
   1354         return parser(parserinfo).parse(timestr, **kwargs)
   1355     else:
-> 1356         return DEFAULTPARSER.parse(timestr, **kwargs)
   1357 
   1358 

~/venvs/env01/lib/python3.6/site-packages/dateutil/parser/_parser.py in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
    646 
    647         if res is None:
--> 648             raise ValueError("Unknown string format:", timestr)
    649 
    650         if len(res) == 0:

ValueError: ('Unknown string format:', 'Tue, 27 Mar 2018 23:48:52 +0800 (GMT+08:00)')
```

This date format with redundant tz info is found in emails sent by Coremail Webmail Server, a Chinese webmail provider.

**Comment by mbdevpl** [comment] 2019-08-19 11:28
Seems related to or duplicate of #453.

Using `dateutil.parser.parse('Tue, 27 Mar 2018 23:48:52 +0800 (GMT+08:00)', fuzzy=True)` solves the problem.

**Closed** 2022-04-21 07:29 UTC
