### ISSUE TITLE
Can't parse "YYYY-02".

### ISSUE THREAD

**Issue by bakfoo** [dateutil/dateutil#69] opened 2015-03-30 08:21 UTC
Here is the error.

```
In [1]: from dateutil.parser import *

In [2]: parse('2014-02')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-f53c0530551b> in <module>()
----> 1 parse('2014-02')

/home/bluetweet/anaconda/lib/python2.7/site-packages/dateutil/parser.pyc in parse(timestr, parserinfo, **kwargs)
    980         return parser(parserinfo).parse(timestr, **kwargs)
    981     else:
--> 982         return DEFAULTPARSER.parse(timestr, **kwargs)
    983
    984

/home/bluetweet/anaconda/lib/python2.7/site-packages/dateutil/parser.pyc in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
    397                 repl[attr] = value
    398
--> 399         ret = default.replace(**repl)
    400
    401         if res.weekday is not None and not res.day:

ValueError: day is out of range for month
```

**Comment by pganssle** [comment] 2015-03-30 11:33
Duplicate of #25. Current proposed solution is PR #30.

**Closed by pganssle** 2015-03-30 11:33 UTC
