### ISSUE TITLE
Parser doesn't use dayfirst and yearfirst when no separator

### ISSUE THREAD

**Issue by cedk** [dateutil/dateutil#81] opened 2015-04-30 10:11 UTC
It always uses the format: YYMMDD or YYYYMMDD despite if yearfirst is set to False or dayfirst is set to True.
I think it should try:
* yearfirst=False and dayfirst=False: MMDDYY
* yearfirst=True and dayfirst=False: YYMMDD
* yearfirst=True and dayfirst=True: YYDDMM
* yearfirst=False and dayfirst=True: DDMMYY

**Comment by pganssle** [comment] 2015-05-11 18:03
Yes, good point. I think that this is easy enough to address. The relevant section of `parser` is [here](https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py#L669), if anyone wants to submit a PR before I get around to fixing it.

**Comment by JeromeBon** [comment] 2016-01-21 12:26
It seems that this issue as been partly fixed in master.

yearfirst=False and dayfirst=False return the correct output
yearfirst=True and dayfirst=False return the correct output
yearfirst=False and dayfirst=True return the correct output
But yearfirst=True and dayfirst=True give the same output as yearfirst=True and dayfirst=False (YYMMDD) instead of YYDDMM

If you confirm me that it's not the expected behavior I can try to make a fix.

**Closed** 2016-03-27 15:31 UTC
Labels: bug, parser

**Comment by aflag** [comment] 2022-04-08 17:24
Sorry to comment in such old issue. However, we've been postponed updating python-dateutils for years due to this breaking change. We usually want to be able to select between MM/DD/YYYY and DD/MM/YYYY to support dates from the US. However, whenever we see the year first (eg: YYYY-MM-DD) we want the day to always be last. We used to be able to accomplish that by setting `dayfirst=True` and everything worked nicely. However, since this change, that doesn't work anymore and we've been having a lot of issues migrating to a newer version of the library. Do you have any advice for us?

**Comment by Daudongit** [comment] 2022-04-13 18:34
@aflag  I also run into the same issue, I end up using the below snippest
you can get more context here (https://stackoverflow.com/questions/51100878/dateutil-parser-how-to-deal-with-dd-mm-and-mm-dd-in-same-column)

```
from dateutil import parser

def parse_date(date_str):
    try:
        return parser.isoparse(date_str)
    except ValueError:
        return parser.parse(date_str, dayfirst=True)
```

**Comment by mariocj89** [comment] 2022-04-18 09:16
If you know the formats, which seems to be the case, https://github.com/dateutil/dateutil/pull/1176  should help. Let me fix the CI and try pushing that for the next release.

**Comment by aflag** [comment] 2022-04-21 10:04
@mariocj89 that seems interesting, but what I don't necessarily know the format, I just know that YYYY-dd-mm will never be it.
