### ISSUE TITLE
Failed to parse line error in 2.4.2

### ISSUE THREAD

**Issue by tBaxter** [dateutil/dateutil#145] opened 2015-11-02 15:06 UTC
I don't see this in 2.4.0, but I do in 2.4.2. I'm not really sure what's happening with it, though.

https://travis-ci.org/tBaxter/vobject/jobs/88801271

**Comment by DamienCassou** [comment] 2015-11-24 09:48
Any news about this? It makes packaging harder.

**Comment by tBaxter** [comment] 2015-12-02 21:45
Any comment at all?

**Comment by pganssle** [comment] 2015-12-04 01:31
@DamienCassou @tBaxter Sorry, I've been out of the country for a while and before that I was busy with other things.

I took a look at this briefly when first reported but it's not easy to trace back the problem in your code, with which I am unfamiliar. I can probably do it eventually, but it would likely speed things up if you could post something close to a minimal working example.

**Comment by tBaxter** [comment] 2015-12-04 14:34
Is the Travis link above not helpful? Clearly it's something that changed between 2.4 and 2.4.2. 
In particular, this line: 
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/dateutil/rrule.py", line 1004, in rebuild
    i += (7-self.wdaymask[i]+wday) % 7
TypeError: list indices must be integers, not float

**Comment by pganssle** [comment] 2015-12-04 14:53
Like I said, there's almost certainly enough information to figure out the problem. The main reason that I'd prefer an MWE is because otherwise I would need to go through and extract the relevant portions of your test in order to replicate the issue in my own system. If you don't have time to prepare one don't worry about it, I appreciate the report in any case. :)

**Comment by pypingou** [comment] 2016-02-15 15:15
Ok so it seems that the problem is in ``rrule.weekday`` that for some reason has: ``SU(+1)`` being in fact ``SU(+1.0)``, so not an int but a float and thus the error.

We could do an easy fix by ensure at: https://github.com/dateutil/dateutil/blob/master/dateutil/rrule.py#L65 that ``n`` is an int, but I'm strill trying to figure out why it becoming an int.

**Comment by pypingou** [comment] 2016-02-15 15:28
Ok found it, and it's in vobject :)

**Comment by pypingou** [comment] 2016-02-15 15:33
I think this can be closed now :)

**Comment by pganssle** [comment] 2016-02-15 21:11
@pypingou Glad to hear it. Do you know why it worked with 2.4.0 and not with 2.4.2?

**Comment by pypingou** [comment] 2016-02-15 21:28
No I investigated the current source code but didn't check its history, "I leave this as an exercise to the reader" :-D

**Comment by pganssle** [comment] 2016-03-08 18:34
Not really sure what all the moving parts are, but neither versions 2.4.0 nor 2.4.2 even *supported* the `SU(+1)` format. I'm closing as presumably irrelevant now.

**Closed by pganssle** 2016-03-08 18:34 UTC
Labels: bug, rrule

**Comment by tBaxter** [comment] 2016-03-08 18:48
Agreed.
