### ISSUE TITLE
TZID is not supported in rrule DTSTART

### ISSUE THREAD

**Issue by ryanpetrello** [dateutil/dateutil#614] opened 2018-01-18 22:00 UTC
```python
from dateutil import rrule
rrule.rrulestr('DTSTART;TZID=America/New_York:20180119T130000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=7')

File "~/venvs/tmp-c74b801dfc74a8d7/lib/python2.7/site-packages/dateutil/rrule.py", line 1616, in __call__
  return self._parse_rfc(s, **kwargs)
File "~/venvs/tmp-c74b801dfc74a8d7/lib/python2.7/site-packages/dateutil/rrule.py", line 1569, in _parse_rfc
  raise ValueError("unsupported DTSTART parm: "+parm)
ValueError: unsupported DTSTART parm: TZID=AMERICA/NEW_YORK
```

From https://www.rfc-editor.org/rfc/rfc5545.txt:

>       The following are examples of this property parameter:
> 
>        DTSTART;TZID=America/New_York:19980119T020000
> 
>        DTEND;TZID=America/New_York:19980119T030000
> 
>       The "TZID" property parameter MUST NOT be applied to DATE
>       properties and DATE-TIME or TIME properties whose time values are
>       specified in UTC.

Is there a way to accomplish this in `dateutil` that I'm unaware of?

**Comment by pganssle** [comment] 2018-01-18 22:20
@ryanpetrello Well, for one thing those `TZID`s are supposed to refer to a a time zone defined elsewhere in the `iCalendar`, they're not supposed to be generic and pulled from a database or something (though I think a lot of people probably *do* use IANA zones like that, and allow the definition to be implicit).

Additionally, your example is actually specifying *two* time zones here, because the datetime is specified as `20180119T130000Z` - where `Z` means "UTC". So I think there would be a conflict either way.

For now, there is a non-ideal way to get what you want, which is to encode the time zone into the `DTSTART` parameter in a different way (unfortunately you have to use the 3-letter acronym because of a well-known limitation of `dateutil.parser.parse`).

```python
from dateutil import rrule
NEW_YORK = tz.gettz('America/New_York')

rrstr = ('DTSTART:20180119T130000EST ' +
         'RRULE:' + 
            'FREQ=DAILY;' +
            'INTERVAL=1;' +
            'COUNT=7')

rr = rrule.rrulestr(rrstr, tzinfos={'EST': NEW_YORK, 'EDT': NEW_YORK)})
```

Long term, I think the way to fix this is to just make it so that the `TZID=` parameter is parsed and the value is looked up in `tzinfos`. Possibly the default value of `tzinfos` can be `dateutil.tz.gettz`.

**Comment by ryanpetrello** [comment] 2018-01-18 22:22
@pganssle yep, that `Z` is a typo on my part.

This workaround is interesting, I might be able to work with that.  Thanks!

**Comment by pganssle** [comment] 2018-01-18 22:33
One thing to note, I would be *somewhat* cautious about using `rrule` with non-monotonic time zones like this. It's *mostly* fine, but the problem is that `rrule` will not try to resolve imaginary or ambiguous times, so for all ambiguous times you'll always get the DST side (no way to specify which side it lands on), and `rrule` will erroneously generate imaginary times, e.g.:

```python
from datetime import datetime
from dateutil import tz, rrule

dtstart = datetime(2017, 3, 12, 1, 30, tzinfo=tz.gettz('America/New_York'))

rr = rrule.rrule(dtstart=dtstart,
                 freq=rrule.HOURLY,
                 count=3)

for dt in rr:
    print('%s: %s' % (str(dt), tz.datetime_exists(dt)))
# 2017-03-12 01:30:00-05:00: True
# 2017-03-12 02:30:00-04:00: False
# 2017-03-12 03:30:00-04:00: True
```

I think that strictly speaking the RFC says that all imaginary datetime should be simply *skipped*, so this is a bug in `dateutil`'s `rrule` implementation and that bug may be fixed in the future (possibly soon).

If you want finer control over how these edge cases are handled, it's better to generate naive datetimes and then attach a time zone to them as desired.

**Comment by ryanpetrello** [comment] 2018-01-18 22:52
@pganssle how do you feel about something like this?

```diff
diff --git a/dateutil/rrule.py b/dateutil/rrule.py
index 4074451..0d7b0eb 100644
--- a/dateutil/rrule.py
+++ b/dateutil/rrule.py
@@ -20,6 +20,7 @@ from six.moves import _thread, range
 import heapq
 
 from ._common import weekday as weekdaybase
+from . import tz
 
 # For warning about deprecation of until and count
 from warnings import warn
@@ -1565,6 +1566,13 @@ class _rrulestr(object):
                     value_found = False
                     valid_values = {"VALUE=DATE-TIME", "VALUE=DATE"}
                     for parm in parms:
+                        if parm.startswith("TZID="):
+                            tzid = parm.split('TZID=')[-1]
+                            if tzinfos is None:
+                                tzinfos = {}
+                            tzinfos['TZID'] = tz.gettz(tzid)
+                            value = value+'TZID'
+                            continue
                         if parm not in valid_values:
                             raise ValueError("unsupported DTSTART parm: "+parm)
                         else:
```

It seems to give me what I want in my example code:

```python
from dateutil import rrule, tz
rule = rrule.rrulestr('DTSTART;TZID=America/New_York:20180310T130000 RRULE:FREQ=DAILY;INTERVAL=1;COUNT=5')
for o in rule:
    print o
    print o.astimezone(tz.tzutc())
    print '-'*20
```

```shell
~ python test_tzid.py
2018-03-10 13:00:00-05:00
2018-03-10 18:00:00+00:00
--------------------
2018-03-11 13:00:00-04:00
2018-03-11 17:00:00+00:00
--------------------
2018-03-12 13:00:00-04:00
2018-03-12 17:00:00+00:00
--------------------
2018-03-13 13:00:00-04:00
2018-03-13 17:00:00+00:00
--------------------
2018-03-14 13:00:00-04:00
2018-03-14 17:00:00+00:00
--------------------
```

**Closed** 2018-03-11 13:57 UTC
Labels: enhancement, help wanted, medium-difficulty, rrule
