### ISSUE TITLE
float values not handled

### ISSUE THREAD

**Issue by Mistress-Anna** [dateutil/dateutil#119] opened 2015-09-04 12:17 UTC
From the documentation, it is not clear that float values are not handled. Also, when passing float values, no exceptions are raised, until using it with datetimes:

```
In [72]: dateutil.relativedelta.relativedelta(years=1.5)
Out[72]: relativedelta(years=+1)

In [73]: dateutil.relativedelta.relativedelta(years=1.5).years
Out[73]: 1.5

In [74]: dateutil.relativedelta.relativedelta(years=1.5)+datetime.datetime.now()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[...]
```

Also, multiplication silently truncates it:
```
In [75]: (dateutil.relativedelta.relativedelta(years=1)*1.5).years
Out[75]: 1
```

There should at least be exceptions raised.
A better fix (for me), would be to handle float values, but I didn't really think if complicated or unfixable cases could appear.

**Comment by pganssle** [comment] 2015-09-04 12:24
@Mistress-Anna This feature was requested in #40 and I've started some work on it in [this branch](https://github.com/dateutil/dateutil/tree/relativedelta-floats). The biggest problem is how to deal with fractions of timespans that are not well-defined. For example, how long is half a month? How long is half a year? (Halfway between Feb 1, 2012 and Feb 1, 2013 is a different duration than between Feb 1, 2013 and Feb 1, 2014).

I think the right approach is to handle it similar to how `timedelta` handles floats, namely throwing an error on construction if floats are passed to arguments where it would not be meaningful.

**Comment by pganssle** [comment] 2015-09-04 12:25
Closing as duplicate of #40.

**Closed by pganssle** 2015-09-04 12:25 UTC
Labels: duplicate, relativedelta
