### ISSUE TITLE
need option to raise error instead of adding time parameters from default

### ISSUE THREAD

**Issue by Casyfill** [dateutil/dateutil#261] opened 2016-04-27 03:52 UTC
I like dateutil parse functionality, but for a particular task, I need to drop any timestamps which lack day information. How can I achieve that result?

**Comment by pganssle** [comment] 2016-04-27 12:02
@Casyfill There is currently no "official" way to do this. This is essentially a duplicate of #125.

There are, as far as I can see, two hack-y ways to do this as a workaround in the meantime. Probably the "better" hack-y way to do it (which doesn't rely on the private interface at all) is to run the parser twice with different `default` dates, and make sure that the `day` value doesn't change between them:

```
from dateutil import parser
from datetime import datetime, time

def parse_with_day(dtstr):
    df1 = datetime.combine(datetime.now().date(), time(0, 0)).replace(day=1)
    df2 = df1.replace(day=15)
    
    d1 = parser.parse(dtstr, default=df1)
    d2 = parser.parse(dtstr, default=df2)

    if d1.day == d2.day:
        print("Has date: {}".format(d1))
    else:
        print("No date")

with_day = "March 7, 2008"
sans_day = "March 2008"

parse_with_day(with_day)
parse_with_day(sans_day)
```

The more fragile approach that _doesn't_ involve parsing the same date twice is to subclass `parser` and add a check for the date into the `_parse` method. This is probably more elegant, but relies on the private interface, which may change in future versions:

```python
from dateutil import parser
from datetime import datetime, time

class NoDayPresentError(ValueError):
    pass


class strictparser(parser.parser):
    def _check_result_for_day(self, result):
        day_value = getattr(result, 'day')

        if getattr(result, 'day', None) is None:
            raise NoDayPresentError

    def _parse(self, *args, **kwargs):
        res, skipped_tokens = super(strictparser, self)._parse(*args, **kwargs)

        self._check_result_for_day(res)

        return res, skipped_tokens


DEFAULT_SP = strictparser()

def parse_with_day(dtstr):
    try:
        dt = DEFAULT_SP.parse(dtstr)
        print('Has date: {}'.format(dt))
    except NoDayPresentError:
        print('No day present')

sp = strictparser()

with_day = "March 7, 2008"
sans_day = "March 2008"

parse_with_day(with_day)
parse_with_day(sans_day)
```

**Comment by Casyfill** [comment] 2016-04-27 13:55
Paul,
thank you very much for the detailed answer.

Indeed, it was very useful - I “invented” the first approach by myself, but
second one looks much more neat.
thank you again!

**Closed** 2016-04-27 15:47 UTC
Labels: duplicate, enhancement, parser
