### ISSUE TITLE
rrule does not play well with pytz tzinfo at daylight savings?

### ISSUE THREAD

**Issue by jeinarsson** [dateutil/dateutil#641] opened 2018-03-16 17:00 UTC
Hi again, it's not clear if this is a dateutil bug, but it's at least a problem for users:

I parse a calendar with the `icalendar` package which returns datetimes localized with `pytz`.

Problem:
When using rrule to expand a recurring event, the occurences do not seem to respect Daylight savings. Here's a stand alone example:

```python
from datetime import datetime, timedelta,timezone
from dateutil.rrule import rrulestr
from pytz import timezone as pytz_tz
from dateutil import tz as du_tz
import dateutil.parser as dp

RRULE='FREQ=WEEKLY;BYDAY=TU,TH;UNTIL=20180317T065959Z'
DTSTART='20180116T130000'

# localize datetime with pytz (like icalendar package)
zone = pytz_tz('America/Los_Angeles')
start = dp.parse(DTSTART)
start = zone.localize(start)

r=rrulestr(RRULE, dtstart=start)
n=datetime(year=2018, month=3, day=7,tzinfo=timezone.utc)
for d in r.between(n,n+timedelta(days=7)):
	print(d, d.tzinfo)
```

Output
```
2018-03-08 13:00:00-08:00 America/Los_Angeles
2018-03-13 13:00:00-08:00 America/Los_Angeles
```

But in America/Los_Angeles Daylight savings started on March 11, so I expect offset -07:00 on March 13.

If I convert the tzinfo of the start date to a dateutil timezone, by:

```python
# fix: replace tzinfo with corresponding dateutil tz
du_zone = du_tz.gettz(str(zone))
start=start.replace(tzinfo=du_zone)
```

The output is
```
2018-03-08 13:00:00-08:00 tzfile('/usr/share/zoneinfo/America/Los_Angeles')
2018-03-13 13:00:00-07:00 tzfile('/usr/share/zoneinfo/America/Los_Angeles')
```

But, for reference, with `zone = pytz_tz('America/Los_Angeles')` I get
```python
>>> str(zone.localize(datetime.datetime(2018,3,8,13)))
'2018-03-08 13:00:00-08:00'
>>> str(zone.localize(datetime.datetime(2018,3,13,13)))
'2018-03-13 13:00:00-07:00'
``` 
I cannot figure out at what point this information is lost.

Again, it is unclear to me if this is an error of pytz or dateutil, but either way it is likely of interest to the community. Thanks!

EDIT: I should say I do this in Python 3.6

**Comment by pganssle** [comment] 2018-03-16 20:14
I would recommend not using `pytz` for this (and in fact, I would recommend not using it at all).

You can see [this not yet released blog post](https://blog.ganssle.io/drafts/pytz-fastest-footgun.html) where I go into detail about the differences between `pytz` and `dateutil`'s timezone models. I also cover it in [this talk](https://www.youtube.com/watch?v=l4UCKCo9FWY), if you're more of a video person.

The difference here is that `pytz` eagerly calculates offsets when you call `localize` on a given `datetime`, whereas the Python model intends these offsets to be calculated lazily on demand.

This is a duplicate of #102 and #88. The strategies you can use here are:

1. Switch to using `dateutil.tz`, in which case it will more or less just work
2. Strip off the time zone before generating the datetimes and then call `the_timezone.localize` on each `datetime` returned by `rrule`
3. Call `dt.tzinfo.normalize(dt)` on the results of all your `rrule` outputs.

As I mentioned above, I recommend the first option.

**Closed by pganssle** 2018-03-16 20:14 UTC
Labels: duplicate, rrule, wontfix

**Comment by jeinarsson** [comment] 2018-03-16 20:54
Thanks, sorry, I should've found #102 and #88. 

> The difference here is that pytz eagerly calculates offsets when you call localize on a given datetime, whereas the Python model intends these offsets to be calculated lazily on demand.

That explains the observed behavior.

In my case I happened to use icalendar which uses pytz internally, which silently leads to bad output. As a blissfully ignorant dateutil user I would appreciate a warning if rrule could detect pytz tzinfo's, but I of course respect if you'd prefer to not clutter your code with checks for obscure incompatabilities..

**Comment by pganssle** [comment] 2018-03-16 21:03
Yeah that is quite fraught, and it's really a pytz problem, not a dateutil problem. I think trying to prevail on icalendar to drop their unnecessary pytz dependency might be better, since they are apparently doing entirely the wrong thing.

**Comment by jeinarsson** [comment] 2018-03-16 21:35
I agree. A helpful warning from dateutil is more like band-aid while the world tries to agree on how to deal with tzinfo.
