### ISSUE TITLE
Overflow on 32 bit system

### ISSUE THREAD

**Issue by kkroo** [dateutil/dateutil#246] opened 2016-04-07 17:23 UTC
I am running python2.7 and am getting an overflow error here:
This is a known limitation in python2.7 where on 32 bit systems, an int is only 32 bits. Instead we want to instantiate to a long or a BitInt instance

```
>>> from dateutil.parser import parse 
>>> parse('20160407061740404') 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>   
File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1008, in parse    
return DEFAULTPARSER.parse(timestr, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 404, in parse                                                                                                               ret = default.replace(**repl)
OverflowError: Python int too large to convert to C long
```

**Comment by pganssle** [comment] 2016-04-07 17:53
@kkroo This is partially a duplicate of #58, though your actual problem is that you have included a 3-digit millisecond value in your timestamp, which is not a format recognized by the parser. The parser counts the digits, sees that it's not in a recognizable format and decides that it must be the year, then passes that number to `datetime`.

```python
from dateutil import parser
parser.parse('20160407061740')
datetime.datetime(2016, 4, 7, 6, 17, 40)
```

I think a format more like `'20160407T061740.404'` would be advisable.

**Closed** 2016-04-08 20:56 UTC
Labels: duplicate, wontfix
