### ISSUE TITLE
Wrong number of days from a day in February 2022

### ISSUE THREAD

**Issue by uri-rodberg** [dateutil/dateutil#1228] opened 2022-08-04 14:57 UTC
Hi,

I ran `relativedelta` from today (2022-08-04) to date 2022-02-14, and I received `relativedelta(months=+5, days=+21)`. If I run `relativedelta` from date 2022-02-14 to today, I receive `relativedelta(months=-5, days=-18)`. Now, 2022-03-04 is exactly 5 months ago, and it's exactly 18 days after 2022-02-14. So the answer should be 5 months, 18 days and not 5 months and 21 days.

I didn't check other dates but I suspect that `relativedelta` always calculates from 31 days in a month.

**Comment by uri-rodberg** [comment] 2022-08-04 15:47
Hi,

I noticed that 2022-07-14 is 5 months after 2022-02-14, and from 2022-07-14 until today there are exactly 21 days. But why does `relativedelta` returns a different number of days backwards? Is this by design?

**Comment by mariocj89** [comment] 2022-08-05 08:58
@uri-rodberg can you provide a code reproducer of what exactly you run, what you get and what you expected?

Relative delta will "just" increment the number you pass.

**Comment by stereodamage** [comment] 2022-08-05 09:34
@mariocj89 I guess what was he doing is
`dt1 = datetime(2022,8, 4)`
`dt2 = datetime(2022, 2, 14)`
`relativedelta(dt1, dt2)`
`Out[1]: relativedelta(months=+5, days=+21)`
`relativedelta(dt2, dt1)`
`Out[2]: relativedelta(months=-5, days=-18)`

But I guess this is how it's done by design, as documentation says:
> order of attributes considered when this relativedelta is
    added to a datetime is:
>    1. Year
>    2. Month
>    3. Day
> ...

Indeed, if we add 5 months to 2022-02-14, then we need to add 21 days to get desired date 2022-08-04. And if we do the same backwards, subtracting 5 months from 2022-08-04 we get 2022-03-04, after that we need to suntract another 18 days to get original 2022-02-14 date.

**Comment by uri-rodberg** [comment] 2022-08-05 09:56
```python
from datetime import date
from dateutil.relativedelta import relativedelta

date1 = date(2022, 8, 4)
date2 = date(2022, 2, 14)
print(date1)
print(date2)

delta = relativedelta(date1, date2)
print(delta)

delta = relativedelta(date2, date1)
print(delta)
```

Output:

```
2022-08-04
2022-02-14
relativedelta(months=+5, days=+21)
relativedelta(months=-5, days=-18)
```

**Comment by uri-rodberg** [comment] 2022-08-05 10:09
If this is done by design, I didn't find it on the documentation.

**Comment by mariocj89** [comment] 2022-08-05 10:13
Yeah that works indeed as intended.

2022-02-14 + 5 months = 2022-07-14
2022-07-14 + 21 days = 2022-07-35 => 2022-08-4

The same logic can be applied in the opposite direction.

It can be indeed confusing. How it is work is documented in https://dateutil.readthedocs.io/en/stable/relativedelta.html#dateutil.relativedelta.relativedelta.

If you want "fixed" time arithmetics (without timezones) you can rely on datetime.timedelta.


Closing as working as designed.

**Closed by mariocj89** 2022-08-05 10:13 UTC

**Comment by uri-rodberg** [comment] 2022-08-05 10:18
Maybe you can add to the docs an example of `relativedelta` of two dates done backwards and forward, and explain the difference between the results?

**Comment by mariocj89** [comment] 2022-08-05 13:28
I want to add a page on time arithmetic that could cover that yeah. Will not be happening any time soon though.

**Comment by uri-rodberg** [comment] 2022-08-05 13:29
Thank you.
