### ISSUE TITLE
Parser ignores dayfirst=True and parses as month first for incompatible string

### ISSUE THREAD

**Issue by jeffsrobertson** [dateutil/dateutil#1140] opened 2021-06-28 02:19 UTC
```
from dateutil import parser
date_string = '10/28/2018'
date = parser.parse(date_string, dayfirst=True)
print(date)
>> 2018-10-28 00:00:00
```

If `dayfirst` is set to `True` and the parser encounters a string which is incompatible with that format, it will silently parse it as `MM/DD/YYYY` (or some other format) without so much as a warning. Is there any way to instead have it raise an error if the given string is incompatible with the specified input parameters? The way it is now basically makes it unusable for my use case, as I'm not able to trust that the parsed results are in fact the format I specified. Thanks!

**Comment by mariocj89** [comment] 2021-06-28 09:53
Hello @jeffsrobertson if you know the format, have you considered using `datetime.datetime.strptime`? Is that an option for you?

If you see the docs of parser.parse, it says "Whether to interpret the first value in an ambiguous 3-integer date", this is intended to be used for deciding what to do on ambiguous input, yours is clearly not.

Can you detail a bit more about your usecase to better understand it?

**Comment by jeffsrobertson** [comment] 2021-06-28 15:52
Hey Mario, thanks for the response. For my use case, I have a list of dates whose format I don't know, just that they're all in the same format  (i.e.`M/D/Y`, `D/M/Y`, or `Y/M/D`). There's a wide variety of ways these dates can be written, i.e. `1/1/20`, `1-1-20`, `January 1st, 2020`, etc, and so I think the date formatting of `datetime.strptime` is too stringent for my use case. What I wanted to do was try to parse every date in all 3 formats, and the format which had the most success would determine the (most likely) correct format.

Essentially, I'm trying to use the success/failure of the parser to determine the date format. But I can't do that because if it successfully parses a date with `dayfirst=True`, I have no idea what format that date is actually in (it could in fact be in `M/D/Y` form).

**Comment by jeffsrobertson** [comment] 2021-06-28 16:24
Just to add, the following example will return a `ParserError`:

```
date_string = '31/2/19'
parsed_date = parser.parse(date_string, dayfirst=True, yearfirst=False)
```

But the following _won't_, and will just parse it as Y/M/D instead:

```
date_string = '32/2/19'
parsed_date = parser.parse(date_string, dayfirst=True, yearfirst=False)
```

So it looks like sometimes it returns a parser error and sometimes it just silently parses in an unspecified format, which you can imagine makes it quite difficult to use reliably.

**Comment by mariocj89** [comment] 2021-06-28 16:52
Yeah, it seems like you are trying to "guess" the format from the parser and that is indeed something that is not exposed through the current parser. I'm not sure if this is something that @pganssle wants to support.

On the other hand, we were considering the other day providing a "ChainParser". Something that would allow you to specify a list of formats and attempt to pass in that specific order (which will allow you to set the order of the formats). Is that something that would help you in this case?

**Comment by jeffsrobertson** [comment] 2021-06-28 22:24
I think I would run into the same issues. Have you considered adding a boolean input parameter like `strict_format=False` to the parser, to give the option of raising an error if the input can't be parsed by the specified format? Something like:

```
parser.parse('1/13/2019', dayfirst=True, strict_format=True)
>> raise ParserError('...')
```

IMO having this optional flag would make a lot of sense for a lot of developer use cases.

**Comment by mariocj89** [comment] 2021-06-29 06:37
> What I wanted to do was try to parse every date in all 3 formats, and the format which had the most success would determine the (most likely) correct format

If you know the three formats, wouldn't then chaining the three format parsers work for you? As in, trying them in order?

I'll speak offline with @pganssle but I think we won't have anything like "strict_format" as the parser does not take a format right now, it just has options to distinguish ambiguous situations.

**Comment by pganssle** [comment] 2021-06-29 17:31
The fundamental issue here is that the parser is not designed for any sort of "strict" date formatting. The way it works is that it assumes that the strings you feed it are valid dates and it tries to map them as best it can onto a `datetime.datetime` object. This is a trade-off that is built deep into the parser's logic and there's not really a way to change it without breaking a bunch of already working code.

`dayfirst` and `yearfirst` are for resolving how dates are parsed when they are ambiguous, so if you have `03/02/01` and you choose `dayfirst=True` and `yearfirst=False`, that date will be parsed as `DD/MM/YY`. If you have something that is an _unambiguously valid date_ like `99/01/27`, `dayfirst` and `yearfirst` will never be consulted, because there is no ambiguity.

Unfortunately, it seems that `dateutil.parser.parse` is not the right tool for your operation.

The way the parser works it is difficult to extract the format in a useful and meaningful way, though it would be a very useful feature and if we could do it right we'd love that. Possibly in the future we can come up with something like an `infer_format` function that is separate from the parser, to avoid the major issue which is "everything that currently parses correctly with the parser should continue to parse correctly" — with a new API we can make different trade-offs.

**Comment by pganssle** [comment] 2021-06-29 17:33
I'm closing this as `wontfix`, though you may feel free to continue to respond here. It may also be a duplicate of similar issues, as this _type_ of issue comes up constantly and unfortunately the parser is a complete pain to maintain or change, and so parser issues tend to languish ☹

**Closed by pganssle** 2021-06-29 17:33 UTC
Labels: enhancement, parser, wontfix
