### ISSUE TITLE
Parse failure

### ISSUE THREAD

**Issue by jnewlin1970** [dateutil/dateutil#172] opened 2016-01-29 19:28 UTC
In an older version we used to be able to do:

dateutil.parser.parse('10/23,20:20')

Fails in the latest version, replacing the comma with space works.

**Comment by pganssle** [comment] 2016-03-10 00:37
Ah, didn't realize that #203 is a duplicate of this. I'm going to close this one as I already commented on that one.

**Closed by pganssle** 2016-03-10 00:37 UTC
Labels: bug, duplicate, parser
