### ISSUE TITLE
dateutil.parser: GMT != UTC

### ISSUE THREAD

**Issue by MA3STR0** [dateutil/dateutil#356] opened 2017-03-29 14:52 UTC
Hi,
I found strange behavior when UTC string is not parsed the same way as GMT:

```
print parser.parse('2017-03-29T00:00:00 UTC')
2017-03-29 00:00:00+00:00 
print parser.parse('2017-03-29T00:00:00 GMT')
2017-03-29 00:00:00+01:00
```

Could it be because of my local CEST zone? I think it was different during winter time.
Thanks!

**Comment by pganssle** [comment] 2017-04-17 18:13
Duplicate of #349.

**Closed by pganssle** 2017-04-17 18:13 UTC

**Comment by pganssle** [comment] 2017-04-17 19:22
Actually, see #370, not #349.
