### ISSUE TITLE
2.4.1.post1 version in source

### ISSUE THREAD

**Issue by papachoco** [dateutil/dateutil#68] opened 2015-03-29 23:42 UTC
Hello,

The version of the zip file in pypy still is 2.4.1 instead of  2.4.1.post1. So buildout fails to install the egg

Thanks

Carlos

**Comment by pganssle** [comment] 2015-03-30 00:17
@papachoco Can you clarify what you mean by that? Something I can reproduce?

**Comment by papachoco** [comment] 2015-03-30 01:08
Thanks for the reply. It's simply a matter to change the version of __init__.py to 2.4.1.post1

![screen shot 2015-03-29 at 8 06 58 pm](https://cloud.githubusercontent.com/assets/244702/6888858/3921d5f0-d64f-11e4-98b4-54f06e75c043.png)

**Comment by graingert** [comment] 2015-03-30 17:32
having a different version in the source and on PyPI breaks a lot of different things!

now if you do "pip install -U" pip will always attempt to install 2.4.1.post1

**Comment by pganssle** [comment] 2015-03-31 01:01
@graingert Is that a bug?  2.4.1.post1 and 2.4.1 are identical, except 2.4.1.post1 has the test suite included in the source distribution. This does not seem to me to be a problem.

@papachoco I have gotten zc.buildout, but it seems a bit more complicated than pip. Can you provide me some kind of MWE config file or something that can replicate the problem? I can keep uploading .postN versions all day, but I want to make sure that what I'm doing will actually work before I add yet another (dubious) "version" to dateutil. I'll continue fiddling with buildout, but it'll be much faster if I don't have to figure out how to get the problem to occur myself.

**Comment by papachoco** [comment] 2015-03-31 12:09
Paul,

I am attaching a sample of a buildout configuration that replicates the
issue

Thanks

Carlos

**Comment by pganssle** [comment] 2015-03-31 12:17
@papachoco The attachment didn't come through. You can send directly to my e-mail at p.ganssle@gmail.com if you wish.

At this point, I'm thinking maybe the best thing to do is to remove the .post1 files and just leave the `python-dateutil-2.4.1.tar.bz2` file up there (which is the same as the `.post1` version. I'll also prepare a `2.4.2` bugfix / timezone update release in the next week or so, which will be released properly as a `.tar.gz`. Would that break anyone's workflow?

**Comment by graingert** [comment] 2015-03-31 12:28
The issue is not about the "post1" in general.

The only requirement so as to not break pip 6.0.8 is that the version in "setup.py" **must match** the version in PyPI.

However you set "2.4.1" in setup.py and "2.4.1.post1" in PyPI.

**Comment by graingert** [comment] 2015-03-31 12:30
> At this point, I'm thinking maybe the best thing to do is to remove the .post1 files and just leave the python-dateutil-2.4.1.tar.bz2 file up there (which is the same as the .post1 version. I'll also prepare a 2.4.2 bugfix / timezone update release in the next week or so, which will be released properly as a .tar.gz. Would that break anyone's workflow?

Removing `2.4.1.post1` will break anyone trying to install this specific version, you should just re-release `2.4.1.post1` as `2.4.2`.

**Comment by papachoco** [comment] 2015-03-31 12:31
+1

**Comment by pganssle** [comment] 2015-03-31 12:36
@graingert Who would try to install the `.post1` version? It's identical to the `2.4.1` version - the only reason there's a `post1` version at all is because I didn't realize that you can't delete and re-release source distributions with the same numeric version (the code is identical, but the original source distributions didn't include the test suite because of a bug in I think setuptools).

The only reason I didn't change the version string in the code was because I was under the impression that the `postN` notation was for problems with the build, and that the true "version number" for 2.4.1 and 2.4.1.post1 would be the same.

Since the .post1 distributions are evidently broken anyway, I think that it's best to use my earlier plan.

**Comment by graingert** [comment] 2015-03-31 12:38
@pganssle I did, because I was notified by my build process that python-dateutil had updated, so I bumped the version.

**Comment by pganssle** [comment] 2015-03-31 12:43
Hm. OK. Then I'll leave as is and prepare a 2.4.2 release. I'll need to do a bit of refactoring on the repo, though. Sorry to leave people in a lurch like this.

**Comment by pganssle** [comment] 2015-03-31 19:42
OK, I've generated a 2.4.2 release. Hopefully this hasn't further broken anyone's system and has resolved the ongoing issues.

Sorry about these problems, guys, thanks for the feedback.

**Closed by pganssle** 2015-03-31 19:42 UTC
Labels: build
